// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdqbfuyoktvpkhwcejpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcWJmdXlva3R2cGtod2NlanByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjIyMDcsImV4cCI6MjA2MjEzODIwN30.ADW5sMJoJqdXVcKqXhbKLPqI5GzPIxc2xWI_vOiALQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);